"""Initial database schema

Revision ID: 566df9483fc7
Revises: 
Create Date: 2025-07-18 10:02:55.757993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566df9483fc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentmode',
    sa.Column('payment_mode_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('payment_mode_id')
    )
    op.create_table('transactiontype',
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('transaction_type_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('last_password_change_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_five_passwords', sa.JSON(), nullable=True),
    sa.Column('password_reset_token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('account_verification_token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'moderator', 'support', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('user_id', 'category_name', name='uix_user_category')
    )
    op.create_table('investment',
    sa.Column('investment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investment_name', sa.String(length=104), nullable=False),
    sa.Column('investment_type', sa.String(length=104), nullable=False),
    sa.Column('investment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=104), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=104), nullable=True),
    sa.Column('exchange_symbol', sa.String(length=104), nullable=True),
    sa.Column('amount_invested', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('buy_price_per_unit', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_price_per_unit', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('gain_or_loss', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('compounding_frequency', sa.String(length=104), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_invested > 0', name='Amount invested check'),
    sa.CheckConstraint('buy_price_per_unit > 0', name='Buying price of unit check'),
    sa.CheckConstraint('current_price_per_unit IS NULL OR current_price_per_unit > 0', name='Current price check'),
    sa.CheckConstraint('current_value IS NULL OR current_value > 0', name='Current value check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('investment_id')
    )
    op.create_table('investmentGoal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_name', sa.String(length=104), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=False),
    sa.Column('applies_to_all_investments', sa.Boolean(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('goal_amount > 0', name='goal_amount_check'),
    sa.CheckConstraint('start_date < end_date', name='Start_end_date_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('budget',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('budget_amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('budget_amount > 0', name='chk_budget_amount'),
    sa.CheckConstraint('start_date < end_date', name='chk_Start_end_date'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('budget_id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uix_user_category')
    )
    op.create_table('investment_goal_link',
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['investmentGoal.goal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.investment_id'], ondelete='CASCADE')
    )
    op.create_table('subscription',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['payment_mode_id'], ['paymentmode.payment_mode_id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transactiontype.transaction_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('is_expense', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('payment_mode_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_check'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['payment_mode_id'], ['paymentmode.payment_mode_id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transactiontype.transaction_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('subscription')
    op.drop_table('investment_goal_link')
    op.drop_table('budget')
    op.drop_table('investmentGoal')
    op.drop_table('investment')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('transactiontype')
    op.drop_table('paymentmode')
    # ### end Alembic commands ###
