"""Updated User model 

Revision ID: 7c790e9b3917
Revises: af004b4a620f
Create Date: 2025-06-25 13:51:28.627599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c790e9b3917'
down_revision: Union[str, None] = 'af004b4a620f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login_time')
    op.drop_column('users', 'last_failed_login_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_failed_login_ip', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('last_failed_login_time', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
