"""Updated User model 

Revision ID: af004b4a620f
Revises: 2116fca47136
Create Date: 2025-06-25 12:30:21.912001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af004b4a620f'
down_revision: Union[str, None] = '2116fca47136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_failed_login_ip', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_failed_login_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login_time')
    op.drop_column('users', 'last_failed_login_ip')
    # ### end Alembic commands ###
