"""add user_name to users

Revision ID: f7b9eaa0750a
Revises: 55596e074371
Create Date: 2026-02-12 15:35:49.294355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7b9eaa0750a'
down_revision: Union[str, None] = '55596e074371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.add_column('account', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('account', sa.Column('name', sa.String(length=104), nullable=False))
    op.add_column('account', sa.Column('type', sa.String(length=104), nullable=False))
    op.drop_index(op.f('account_name'), table_name='account')
    op.create_unique_constraint(None, 'account', ['name'])
    op.drop_column('account', 'account_id')
    op.drop_column('account', 'account_type')
    op.drop_column('account', 'account_name')
    op.add_column('budget', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('budget', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('budget_ibfk_2'), 'budget', type_='foreignkey')
    op.create_foreign_key(None, 'budget', 'categories', ['category_id'], ['id'])
    op.drop_column('budget', 'budget_id')
    op.drop_column('budget', 'budget_amount')
    op.add_column('categories', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('categories', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('uix_user_category'), 'categories', type_='unique')
    op.create_unique_constraint('uix_user_category', 'categories', ['user_id', 'name'])
    op.drop_column('categories', 'category_id')
    op.drop_column('categories', 'category_name')
    op.drop_constraint(op.f('investment_ibfk_2'), 'investment', type_='foreignkey')
    op.create_foreign_key(None, 'investment', 'account', ['account_linked'], ['id'])
    op.add_column('paymentmode', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('paymentmode', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('paymentmode', 'payment_mode_id')
    op.drop_column('paymentmode', 'payment_mode')
    op.add_column('subscription', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('subscription', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('subscription', sa.Column('billing_period', sa.Enum('YEARLY', 'HALF_YEARLY', 'QUATERLY', 'WEEKLY', 'ONE_TIME', 'MONTHLY', name='billing_period_enum'), nullable=False))
    op.add_column('subscription', sa.Column('account_id', sa.Integer(), nullable=True))
    op.alter_column('subscription', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('subscription', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(op.f('subscription_ibfk_3'), 'subscription', type_='foreignkey')
    op.drop_constraint(op.f('subscription_ibfk_1'), 'subscription', type_='foreignkey')
    op.drop_constraint(op.f('subscription_ibfk_5'), 'subscription', type_='foreignkey')
    op.drop_constraint(op.f('subscription_ibfk_4'), 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'transactiontype', ['transaction_type_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'paymentmode', ['payment_mode_id'], ['id'])
    op.drop_column('subscription', 'subscription_name')
    op.drop_column('subscription', 'billing_cycle')
    op.drop_column('subscription', 'subscription_id')
    op.drop_column('subscription', 'account_linked')
    op.add_column('transactions', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('transactions_ibfk_1'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_ibfk_5'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_ibfk_3'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_ibfk_4'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'paymentmode', ['payment_mode_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'transactiontype', ['transaction_type_id'], ['id'])
    op.drop_column('transactions', 'transaction_id')
    op.drop_column('transactions', 'transaction_date')
    op.add_column('transactiontype', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('transactiontype', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('transactiontype', 'transaction_type_id')
    op.drop_column('transactiontype', 'transaction_type')
    op.add_column('users', sa.Column('user_name', sa.String(length=255), nullable=False))
    op.drop_index(op.f('username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'user_name')
    op.add_column('transactiontype', sa.Column('transaction_type', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('transactiontype', sa.Column('transaction_type_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('transactiontype', 'name')
    op.drop_column('transactiontype', 'id')
    op.add_column('transactions', sa.Column('transaction_date', mysql.DATETIME(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_ibfk_4'), 'transactions', 'transactiontype', ['transaction_type_id'], ['transaction_type_id'])
    op.create_foreign_key(op.f('transactions_ibfk_3'), 'transactions', 'categories', ['category_id'], ['category_id'])
    op.create_foreign_key(op.f('transactions_ibfk_5'), 'transactions', 'paymentmode', ['payment_mode_id'], ['payment_mode_id'])
    op.create_foreign_key(op.f('transactions_ibfk_1'), 'transactions', 'account', ['account_id'], ['account_id'])
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'id')
    op.add_column('subscription', sa.Column('account_linked', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('subscription_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('subscription', sa.Column('billing_cycle', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('subscription', sa.Column('subscription_name', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_ibfk_4'), 'subscription', 'transactiontype', ['transaction_type_id'], ['transaction_type_id'])
    op.create_foreign_key(op.f('subscription_ibfk_5'), 'subscription', 'paymentmode', ['payment_mode_id'], ['payment_mode_id'])
    op.create_foreign_key(op.f('subscription_ibfk_1'), 'subscription', 'account', ['account_linked'], ['account_id'])
    op.create_foreign_key(op.f('subscription_ibfk_3'), 'subscription', 'categories', ['category_id'], ['category_id'])
    op.alter_column('subscription', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('subscription', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('subscription', 'account_id')
    op.drop_column('subscription', 'billing_period')
    op.drop_column('subscription', 'name')
    op.drop_column('subscription', 'id')
    op.add_column('paymentmode', sa.Column('payment_mode', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('paymentmode', sa.Column('payment_mode_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('paymentmode', 'name')
    op.drop_column('paymentmode', 'id')
    op.drop_constraint(None, 'investment', type_='foreignkey')
    op.create_foreign_key(op.f('investment_ibfk_2'), 'investment', 'account', ['account_linked'], ['account_id'])
    op.add_column('categories', sa.Column('category_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('categories', sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('uix_user_category', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uix_user_category'), 'categories', ['user_id', 'category_name'])
    op.drop_column('categories', 'name')
    op.drop_column('categories', 'id')
    op.add_column('budget', sa.Column('budget_amount', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budget', sa.Column('budget_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.create_foreign_key(op.f('budget_ibfk_2'), 'budget', 'categories', ['category_id'], ['category_id'])
    op.drop_column('budget', 'amount')
    op.drop_column('budget', 'id')
    op.add_column('account', sa.Column('account_name', mysql.VARCHAR(length=104), nullable=False))
    op.add_column('account', sa.Column('account_type', mysql.VARCHAR(length=104), nullable=False))
    op.add_column('account', sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'account', type_='unique')
    op.create_index(op.f('account_name'), 'account', ['account_name'], unique=True)
    op.drop_column('account', 'type')
    op.drop_column('account', 'name')
    op.drop_column('account', 'id')
    op.create_table('transaction',
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('transaction_date', mysql.DATETIME(), nullable=False),
    sa.Column('account_linked', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_expense', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_income', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('payment_mode_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`amount` > 0)', name=op.f('amount_check')),
    sa.ForeignKeyConstraint(['account_linked'], ['account.account_id'], name=op.f('transaction_ibfk_1')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('transaction_ibfk_3')),
    sa.ForeignKeyConstraint(['payment_mode_id'], ['paymentmode.payment_mode_id'], name=op.f('transaction_ibfk_5')),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transactiontype.transaction_type_id'], name=op.f('transaction_ibfk_4')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transaction_ibfk_2')),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
