version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: finance_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: abhinavnaruto
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_container
    command: celery -A api.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql

volumes:
  mysql_data:
