[phases.setup]
# Tells Nixpacks to install Node.js, Python 3.11, and the pip module for 3.11
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.build]
# Your build commands
cmds = ["npm install", "pip install -r requirements.txt"]